// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sistema_rrhh.Data;

namespace sistema_rrhh.Migrations
{
    [DbContext(typeof(BaseDatos))]
    [Migration("20210623155212_empleadohora_primera")]
    partial class empleadohora_primera
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("sistema_rrhh.Data.Empleado", b =>
                {
                    b.Property<string>("Rut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Rut");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("sistema_rrhh.Data.EmpleadoHora", b =>
                {
                    b.Property<string>("EmpleadoRut")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Horas")
                        .HasColumnType("int");

                    b.HasKey("EmpleadoRut", "Fecha");

                    b.ToTable("EmpleadosHoras");
                });

            modelBuilder.Entity("sistema_rrhh.Data.EmpleadoHora", b =>
                {
                    b.HasOne("sistema_rrhh.Data.Empleado", "Empleado")
                        .WithMany("EmpleadoHoras")
                        .HasForeignKey("EmpleadoRut")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("sistema_rrhh.Data.Empleado", b =>
                {
                    b.Navigation("EmpleadoHoras");
                });
#pragma warning restore 612, 618
        }
    }
}
